name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig release.zip'
    - name: Commit Archive and Release
      run: |
        git config --global user.email "88404797+Evakhiin@users.noreply.github.com"
        git config --global user.name "Evakhiin"
        git add release.zip
        git commit -m "Add Archive"
        git push --force
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          files: |
            release.zip