name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Commit Archive
      run: |
        git config --global user.email "88404797+Evakhiin@users.noreply.github.com"
        git config --global user.name "Evakhiin"
        git add release.zip
        git commit -m "Add Archive"
        git push --force
      - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
